language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
env:
  - RAILS_VERSION="~> 4.1.0"
  - RAILS_VERSION="~> 4.2.0"
  - RAILS_VERSION="~> 5.0.0"
  - RAILS_VERSION="~> 5.1.0"
  - RAILS_VERSION="~> 5.2.0"
  - RAILS_VERSION="~> 6.0.0.rc1"
matrix:
  exclude:
    - rvm: 2.4.6
      env: RAILS_VERSION="~> 6.0.0.rc1"
    - rvm: 2.6.3
      env: RAILS_VERSION="~> 4.1.0"
    - rvm: 2.6.3
      env: RAILS_VERSION="~> 4.2.0"
script:
  - cd test/dummy/
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
